// packages/frontend-solid/src/routes/mint.tsx
import { useSearchParams } from '@solidjs/router';
import { createEffect, createMemo, type JSX, on, Show } from 'solid-js';

import { type MarketData, useDashboardMarkets } from '@/features/markets';
import { useUIMode } from '@/providers/UIModeProvider';
import { cn } from '@/shared/lib/utils';
import { Card, CardContent, CardHeader, CardTitle } from '@/shared/ui/Card';
import {
  SelectContent,
  SelectItem,
  SelectRoot,
  SelectTrigger,
  SelectValue,
} from '@/shared/ui/Select';
import { Skeleton } from '@/shared/ui/Skeleton';

/**
 * Mint page - PT/YT minting interface with market selection
 *
 * Features:
 * - Market selection via dropdown with URL persistence
 * - MintForm for minting PT+YT tokens from SY
 * - Responsive layout with market info sidebar
 */
export default function MintPage(): JSX.Element {
  const { isSimple } = useUIMode();
  const [searchParams, setSearchParams] = useSearchParams();

  const { markets, isLoading, isError } = useDashboardMarkets();

  // Get selected market address from URL
  const selectedMarketAddress = createMemo(() => searchParams['market'] ?? null);

  // Find the selected market data
  const selectedMarket = createMemo(() => {
    const address = selectedMarketAddress();
    if (!address) return null;
    return markets().find((m) => m.address === address) ?? null;
  });

  // Auto-select first market if none selected and markets are loaded
  createEffect(
    on(
      () => [markets(), selectedMarketAddress()] as const,
      ([marketList, address]) => {
        if (!address && marketList.length > 0 && marketList[0]) {
          setSearchParams({ market: marketList[0].address }, { replace: true });
        }
      }
    )
  );

  // Handle market selection change
  const handleMarketChange = (market: MarketData | null): void => {
    if (market) {
      setSearchParams({ market: market.address });
    }
  };

  return (
    <div class="mx-auto max-w-7xl px-4 py-8">
      {/* Page Header */}
      <div class="mb-8">
        <h1 class="text-foreground text-3xl font-semibold">
          {isSimple() ? 'Earn Fixed Yield' : 'Mint PT + YT'}
        </h1>
        <p class="text-muted-foreground mt-2">
          {isSimple()
            ? 'Deposit your tokens to lock in guaranteed fixed returns until maturity.'
            : 'Deposit yield-bearing assets to mint Principal Tokens (PT) and Yield Tokens (YT). PT represents fixed yield, YT represents variable yield.'}
        </p>
      </div>

      {/* Loading State */}
      <Show when={isLoading()}>
        <div class="grid gap-6 lg:grid-cols-3">
          <div class="lg:col-span-2">
            <Skeleton class="h-[500px] rounded-lg" />
          </div>
          <div>
            <Skeleton class="h-[300px] rounded-lg" />
          </div>
        </div>
      </Show>

      {/* Error State */}
      <Show when={isError()}>
        <Card>
          <CardContent class="py-8 text-center">
            <p class="text-destructive">Failed to load markets. Please try again later.</p>
          </CardContent>
        </Card>
      </Show>

      {/* No Markets State */}
      <Show when={!isLoading() && !isError() && markets().length === 0}>
        <Card>
          <CardContent class="py-8 text-center">
            <p class="text-muted-foreground">No active markets available for minting.</p>
          </CardContent>
        </Card>
      </Show>

      {/* Main Content */}
      <Show when={!isLoading() && !isError() && markets().length > 0}>
        <div class="grid gap-6 lg:grid-cols-3">
          {/* Mint Form Column */}
          <div class="lg:col-span-2">
            <Card>
              <CardHeader class="flex flex-row items-center justify-between gap-4">
                <CardTitle>{isSimple() ? 'Deposit' : 'Mint Tokens'}</CardTitle>

                {/* Market Selector */}
                <MarketSelector
                  markets={markets()}
                  selectedMarket={selectedMarket()}
                  onSelect={handleMarketChange}
                />
              </CardHeader>
              <CardContent>
                <Show
                  when={selectedMarket()}
                  fallback={
                    <div class="text-muted-foreground py-8 text-center">
                      Select a market to start minting.
                    </div>
                  }
                >
                  {(market) => <MintFormPlaceholder market={market()} isSimple={isSimple()} />}
                </Show>
              </CardContent>
            </Card>
          </div>

          {/* Market Info Sidebar */}
          <div>
            <Show when={selectedMarket()}>
              {(market) => <MarketInfoCard market={market()} isSimple={isSimple()} />}
            </Show>
          </div>
        </div>
      </Show>
    </div>
  );
}

// ============================================================================
// Market Selector Component
// ============================================================================

interface MarketSelectorProps {
  markets: MarketData[];
  selectedMarket: MarketData | null;
  onSelect: (market: MarketData | null) => void;
}

function MarketSelector(props: MarketSelectorProps): JSX.Element {
  // Format market option for display
  const getMarketLabel = (market: MarketData): string => {
    const symbol = market.metadata?.yieldTokenSymbol ?? 'Unknown';
    const apy = market.impliedApy.multipliedBy(100).toFixed(2);
    return `${symbol} (${apy}% APY)`;
  };

  // Get display text for selected market
  const selectedLabel = createMemo(() => {
    const market = props.selectedMarket;
    if (!market) return 'Select a market';
    return getMarketLabel(market);
  });

  return (
    <SelectRoot<MarketData>
      options={props.markets}
      optionValue="address"
      optionTextValue={(m) => m.metadata?.yieldTokenSymbol ?? 'Unknown'}
      value={props.selectedMarket}
      onChange={props.onSelect}
      placeholder="Select a market"
      itemComponent={(itemProps) => (
        <SelectItem item={itemProps.item}>
          <div class="flex items-center justify-between gap-4">
            <span class="font-medium">
              {itemProps.item.rawValue.metadata?.yieldTokenSymbol ?? 'Unknown'}
            </span>
            <span class="text-muted-foreground text-xs">
              {itemProps.item.rawValue.impliedApy.multipliedBy(100).toFixed(2)}% APY
            </span>
          </div>
        </SelectItem>
      )}
    >
      <SelectTrigger class="w-48">
        <SelectValue placeholder="Select a market">{selectedLabel()}</SelectValue>
      </SelectTrigger>
      <SelectContent />
    </SelectRoot>
  );
}

// ============================================================================
// Mint Form Placeholder
// ============================================================================

interface MintFormPlaceholderProps {
  market: MarketData;
  isSimple: boolean;
}

function MintFormPlaceholder(props: MintFormPlaceholderProps): JSX.Element {
  const symbol = createMemo(() => props.market.metadata?.yieldTokenSymbol ?? 'Unknown');
  const apy = createMemo(() => props.market.impliedApy.multipliedBy(100).toNumber());

  return (
    <div class="space-y-6 py-4">
      {/* Info Banner */}
      <div class="bg-primary/5 border-primary/20 rounded-lg border p-4">
        <div class="flex items-start gap-3">
          <div class="bg-primary/10 text-primary flex h-10 w-10 shrink-0 items-center justify-center rounded-full">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <circle cx="12" cy="12" r="10" />
              <path d="M12 16v-4" />
              <path d="M12 8h.01" />
            </svg>
          </div>
          <div>
            <h4 class="text-foreground font-medium">
              {props.isSimple ? 'How it works' : 'Minting PT + YT'}
            </h4>
            <p class="text-muted-foreground mt-1 text-sm">
              {props.isSimple
                ? `Deposit ${symbol()} to lock in a fixed ${apy().toFixed(2)}% APY until maturity. Your returns are guaranteed regardless of rate changes.`
                : `Deposit SY tokens to mint both Principal Tokens (PT) and Yield Tokens (YT). PT gives you fixed yield at ${apy().toFixed(2)}% APY, while YT captures variable yield until expiry.`}
            </p>
          </div>
        </div>
      </div>

      {/* Placeholder Form */}
      <div class="bg-muted/30 rounded-lg border border-dashed p-8 text-center">
        <div class="text-muted-foreground mx-auto mb-4 h-12 w-12">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="48"
            height="48"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <circle cx="12" cy="12" r="10" />
            <path d="M12 8v8" />
            <path d="M8 12h8" />
          </svg>
        </div>
        <h3 class="text-foreground text-lg font-medium">Mint Form Coming Soon</h3>
        <p class="text-muted-foreground mt-2 text-sm">
          The minting interface is being developed. Check back soon!
        </p>
      </div>
    </div>
  );
}

// ============================================================================
// Market Info Card
// ============================================================================

interface MarketInfoCardProps {
  market: MarketData;
  isSimple: boolean;
}

function MarketInfoCard(props: MarketInfoCardProps): JSX.Element {
  const symbol = createMemo(() => props.market.metadata?.yieldTokenSymbol ?? 'Unknown');
  const apy = createMemo(() => props.market.impliedApy.multipliedBy(100).toNumber());
  const daysLeft = createMemo(() => props.market.daysToExpiry);

  const expiryDate = createMemo(() => {
    const date = new Date(props.market.expiry * 1000);
    return date.toLocaleDateString(undefined, {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  });

  return (
    <Card>
      <CardHeader>
        <CardTitle class="text-lg">Market Info</CardTitle>
      </CardHeader>
      <CardContent>
        <div class="space-y-4">
          {/* Token Symbol */}
          <div class="flex items-center justify-between">
            <span class="text-muted-foreground text-sm">Token</span>
            <span class="font-medium">{symbol()}</span>
          </div>

          {/* Implied APY */}
          <div class="flex items-center justify-between">
            <span class="text-muted-foreground text-sm">
              {props.isSimple ? 'Fixed Yield' : 'Implied APY'}
            </span>
            <span class="text-primary font-mono font-semibold">{apy().toFixed(2)}%</span>
          </div>

          {/* Expiry */}
          <div class="flex items-center justify-between">
            <span class="text-muted-foreground text-sm">Expiry Date</span>
            <span class="font-mono text-sm">{expiryDate()}</span>
          </div>

          {/* Days to Expiry */}
          <Show when={!props.market.isExpired}>
            <div class="flex items-center justify-between">
              <span class="text-muted-foreground text-sm">
                {props.isSimple ? 'Time Remaining' : 'Days to Expiry'}
              </span>
              <span class="font-mono text-sm">
                {daysLeft()} {daysLeft() === 1 ? 'day' : 'days'}
              </span>
            </div>
          </Show>

          {/* Expired Badge */}
          <Show when={props.market.isExpired}>
            <div class="bg-destructive/10 text-destructive rounded-lg p-3 text-center text-sm font-medium">
              This market has expired
            </div>
          </Show>

          {/* Oracle Status */}
          <Show when={!props.isSimple}>
            <div class="flex items-center justify-between">
              <span class="text-muted-foreground text-sm">Oracle</span>
              <span
                class={cn(
                  'text-xs font-medium',
                  props.market.oracleState === 'ready' && 'text-success',
                  props.market.oracleState === 'partial' && 'text-warning',
                  props.market.oracleState === 'spot-only' && 'text-muted-foreground'
                )}
              >
                {props.market.oracleState === 'ready' && 'TWAP Ready'}
                {props.market.oracleState === 'partial' && 'Warming Up'}
                {props.market.oracleState === 'spot-only' && 'Spot Only'}
              </span>
            </div>
          </Show>

          {/* What you receive section */}
          <div class="border-border mt-4 border-t pt-4">
            <div class="text-muted-foreground mb-3 text-sm font-medium">
              {props.isSimple ? 'What you get' : 'You will receive'}
            </div>
            <div class="space-y-2">
              <div class="bg-primary/5 flex items-center justify-between rounded-md p-2">
                <span class="text-sm font-medium">PT-{symbol()}</span>
                <span class="text-muted-foreground text-xs">
                  {props.isSimple ? 'Fixed yield' : 'Principal Token'}
                </span>
              </div>
              <Show when={!props.isSimple}>
                <div class="bg-chart-2/10 flex items-center justify-between rounded-md p-2">
                  <span class="text-sm font-medium">YT-{symbol()}</span>
                  <span class="text-muted-foreground text-xs">Yield Token</span>
                </div>
              </Show>
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

// packages/frontend/src/app/mint/page.tsx
'use client';

import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { type ReactNode, Suspense, useEffect, useMemo, useState } from 'react';

import { SimpleEarnForm, SimpleWithdrawForm, WrapToSyForm } from '@features/earn';
import { useDashboardMarkets } from '@features/markets';
import { MintForm } from '@features/mint';
import { UnwrapSyForm } from '@features/redeem';
import { useUIMode } from '@shared/theme/ui-mode-context';
import { SkeletonCard } from '@shared/ui/Skeleton';
import { Tabs, TabsList, TabsTrigger } from '@shared/ui/tabs';

type TabType = 'wrap' | 'split' | 'unwrap';
type SimpleTabType = 'earn' | 'withdraw';

/**
 * Simple mode content - streamlined deposit/withdraw flow
 */
function SimpleModeContent(): ReactNode {
  const searchParams = useSearchParams();
  const marketParam = searchParams.get('market');
  const [mounted, setMounted] = useState(false);
  const [activeTab, setActiveTab] = useState<SimpleTabType>('earn');
  const [selectedMarketAddress, setSelectedMarketAddress] = useState<string | null>(marketParam);

  useEffect(() => {
    setMounted(true);
  }, []);

  const { markets, isLoading, isError } = useDashboardMarkets();

  const selectedMarket = useMemo(() => {
    if (selectedMarketAddress) {
      return markets.find((m) => m.address === selectedMarketAddress);
    }
    if (marketParam) {
      return markets.find((m) => m.address === marketParam);
    }
    return markets[0];
  }, [markets, marketParam, selectedMarketAddress]);

  useEffect(() => {
    if (markets.length > 0 && !selectedMarketAddress && !marketParam) {
      setSelectedMarketAddress(markets[0]?.address ?? null);
    }
  }, [markets, selectedMarketAddress, marketParam]);

  return (
    <div className="space-y-8">
      <div className="grid gap-8 lg:grid-cols-2">
        {/* Form Section */}
        <div>
          {/* Market Selector */}
          {markets.length > 1 && (
            <div className="mb-4">
              <label className="text-foreground mb-2 block text-sm font-medium">Select Asset</label>
              <select
                value={selectedMarket?.address ?? ''}
                onChange={(e) => {
                  setSelectedMarketAddress(e.target.value);
                }}
                className="border-border bg-muted text-foreground focus:border-primary focus:ring-primary w-full rounded-lg border px-4 py-3 focus:ring-1 focus:outline-none"
              >
                {markets.map((m) => (
                  <option key={m.address} value={m.address}>
                    {m.metadata?.yieldTokenSymbol ?? m.address.slice(0, 10)} -{' '}
                    {m.metadata?.yieldTokenName ?? 'Unknown'}
                  </option>
                ))}
              </select>
            </div>
          )}

          {/* Simple Tabs */}
          <Tabs
            value={activeTab}
            onValueChange={(value) => {
              setActiveTab(value as SimpleTabType);
            }}
            className="space-y-4"
          >
            <TabsList className="w-full">
              <TabsTrigger value="earn" className="flex-1">
                Deposit
              </TabsTrigger>
              <TabsTrigger
                value="withdraw"
                className="data-active:bg-chart-1 data-active:text-foreground flex-1"
              >
                Withdraw
              </TabsTrigger>
            </TabsList>

            {/* Form */}
            {!mounted || isLoading ? (
              <SkeletonCard className="h-[500px]" />
            ) : isError ? (
              <div className="border-destructive/20 bg-destructive/10 rounded-lg border p-8 text-center">
                <p className="text-destructive">Failed to load markets. Please try again.</p>
              </div>
            ) : !selectedMarket ? (
              <div className="border-border bg-card rounded-lg border p-8 text-center">
                <p className="text-muted-foreground">No markets available.</p>
                <p className="text-muted-foreground mt-2 text-sm">
                  Markets will appear here once they are created.
                </p>
              </div>
            ) : activeTab === 'earn' ? (
              <SimpleEarnForm market={selectedMarket} />
            ) : (
              <SimpleWithdrawForm market={selectedMarket} />
            )}
          </Tabs>
        </div>

        {/* Info Panel - Simplified */}
        <div className="space-y-4">
          <div className="border-border bg-card rounded-lg border p-6">
            <h2 className="text-foreground text-lg font-semibold">
              {activeTab === 'withdraw' ? 'How Withdrawing Works' : 'How Earning Works'}
            </h2>

            <div>
              {activeTab === 'withdraw' ? (
                <div className="text-muted-foreground mt-4 space-y-4 text-sm">
                  <div className="flex gap-3">
                    <div className="bg-chart-1/30 text-chart-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      1
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Select Amount</p>
                      <p className="mt-1">Choose how much of your position you want to withdraw.</p>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <div className="bg-chart-1/20 text-chart-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      2
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Receive Tokens</p>
                      <p className="mt-1">
                        Your position is converted back to the original tokens in a single
                        transaction.
                      </p>
                    </div>
                  </div>

                  <div className="border-chart-1/30 bg-chart-1/10 mt-4 rounded-lg border p-3">
                    <p className="text-chart-1 text-sm">
                      <span className="font-medium">Note:</span> Withdrawing before maturity
                      requires equal Fixed-Rate and Variable-Rate positions.
                    </p>
                  </div>
                </div>
              ) : (
                <div className="text-muted-foreground mt-4 space-y-4 text-sm">
                  <div className="flex gap-3">
                    <div className="bg-primary/30 text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      1
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Deposit Tokens</p>
                      <p className="mt-1">
                        Deposit your yield-bearing tokens (like sSTRK) into the protocol.
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <div className="bg-primary/20 text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      2
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Receive Positions</p>
                      <p className="mt-1">
                        You receive a Fixed-Rate Position (guaranteed yield) and a Variable-Rate
                        Position (floating yield).
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <div className="bg-primary/20 text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      3
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Earn Yield</p>
                      <p className="mt-1">
                        Hold until maturity to earn the fixed rate, or withdraw anytime.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              <div className="bg-muted mt-6 rounded-lg p-4">
                <h3 className="text-foreground text-sm font-medium">Position Types</h3>
                <dl className="mt-2 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <dt className="text-muted-foreground">Fixed-Rate</dt>
                    <dd className="text-foreground">Guaranteed yield at maturity</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="text-muted-foreground">Variable-Rate</dt>
                    <dd className="text-foreground">Floating yield until maturity</dd>
                  </div>
                </dl>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * Advanced mode content - original tabbed interface
 */
function AdvancedModeContent(): ReactNode {
  const searchParams = useSearchParams();
  const marketParam = searchParams.get('market');
  const tabParam = searchParams.get('tab');
  const [mounted, setMounted] = useState(false);
  const [activeTab, setActiveTab] = useState<TabType>(
    tabParam === 'split' ? 'split' : tabParam === 'unwrap' ? 'unwrap' : 'wrap'
  );
  const [selectedMarketAddress, setSelectedMarketAddress] = useState<string | null>(marketParam);

  useEffect(() => {
    setMounted(true);
  }, []);

  const { markets, isLoading, isError } = useDashboardMarkets();

  const selectedMarket = useMemo(() => {
    if (selectedMarketAddress) {
      return markets.find((m) => m.address === selectedMarketAddress);
    }
    if (marketParam) {
      return markets.find((m) => m.address === marketParam);
    }
    return markets[0];
  }, [markets, marketParam, selectedMarketAddress]);

  useEffect(() => {
    if (markets.length > 0 && !selectedMarketAddress && !marketParam) {
      setSelectedMarketAddress(markets[0]?.address ?? null);
    }
  }, [markets, selectedMarketAddress, marketParam]);

  return (
    <div className="space-y-8">
      <div className="grid gap-8 lg:grid-cols-2">
        {/* Form Section */}
        <div>
          {/* Market Selector */}
          {markets.length > 1 && (
            <div className="mb-4">
              <label className="text-foreground mb-2 block text-sm font-medium">Select Asset</label>
              <select
                value={selectedMarket?.address ?? ''}
                onChange={(e) => {
                  setSelectedMarketAddress(e.target.value);
                }}
                className="border-border bg-muted text-foreground focus:border-primary focus:ring-primary w-full rounded-lg border px-4 py-3 focus:ring-1 focus:outline-none"
              >
                {markets.map((m) => (
                  <option key={m.address} value={m.address}>
                    {m.metadata?.yieldTokenSymbol ?? m.address.slice(0, 10)} -{' '}
                    {m.metadata?.yieldTokenName ?? 'Unknown'}
                  </option>
                ))}
              </select>
            </div>
          )}

          {/* Tabs */}
          <Tabs
            value={activeTab}
            onValueChange={(value) => {
              setActiveTab(value as TabType);
            }}
            className="space-y-4"
          >
            <TabsList className="w-full">
              <TabsTrigger value="wrap" className="flex-1">
                Deposit
              </TabsTrigger>
              <TabsTrigger value="split" className="flex-1">
                Split
              </TabsTrigger>
              <TabsTrigger
                value="unwrap"
                className="data-active:bg-chart-1 data-active:text-foreground flex-1"
              >
                Withdraw
              </TabsTrigger>
            </TabsList>

            {/* Form */}
            {!mounted || isLoading ? (
              <SkeletonCard className="h-[500px]" />
            ) : isError ? (
              <div className="border-destructive/20 bg-destructive/10 rounded-lg border p-8 text-center">
                <p className="text-destructive">Failed to load markets. Please try again.</p>
              </div>
            ) : !selectedMarket ? (
              <div className="border-border bg-card rounded-lg border p-8 text-center">
                <p className="text-muted-foreground">No markets available.</p>
                <p className="text-muted-foreground mt-2 text-sm">
                  Markets will appear here once they are created.
                </p>
              </div>
            ) : activeTab === 'wrap' ? (
              <WrapToSyForm market={selectedMarket} />
            ) : activeTab === 'split' ? (
              <MintForm market={selectedMarket} />
            ) : (
              <UnwrapSyForm market={selectedMarket} />
            )}
          </Tabs>
        </div>

        {/* Info Panel */}
        <div className="space-y-4">
          <div className="border-border bg-card rounded-lg border p-6">
            <h2 className="text-foreground text-lg font-semibold">
              {activeTab === 'unwrap' ? 'How Withdrawing Works' : 'How Splitting Works'}
            </h2>

            <div>
              {activeTab === 'unwrap' ? (
                <div className="text-muted-foreground mt-4 space-y-4 text-sm">
                  <div className="flex gap-3">
                    <div className="bg-chart-1/30 text-chart-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      1
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Withdraw Your Tokens</p>
                      <p className="mt-1">
                        Convert your deposited tokens back to the underlying yield-bearing token
                        (like sSTRK).
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <div className="bg-chart-1/20 text-chart-1 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      2
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Continue Earning</p>
                      <p className="mt-1">
                        Your yield-bearing tokens will continue earning yield in your wallet or can
                        be used in other DeFi protocols.
                      </p>
                    </div>
                  </div>

                  <div className="border-chart-1/30 bg-chart-1/10 mt-4 rounded-lg border p-3">
                    <p className="text-chart-1 text-sm">
                      <span className="font-medium">Note:</span> This only converts SY tokens back
                      to the underlying token. If you have PT or YT, use Redeem in Portfolio to
                      convert them to SY first.
                    </p>
                  </div>
                </div>
              ) : (
                <div className="text-muted-foreground mt-4 space-y-4 text-sm">
                  <div className="flex gap-3">
                    <div
                      className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium ${
                        activeTab === 'wrap'
                          ? 'bg-primary/30 text-primary'
                          : 'bg-primary/20 text-primary'
                      }`}
                    >
                      1
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Deposit Tokens</p>
                      <p className="mt-1">
                        Deposit your yield-bearing tokens (like sSTRK) into the protocol.
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <div
                      className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium ${
                        activeTab === 'split'
                          ? 'bg-primary/30 text-primary'
                          : 'bg-primary/20 text-primary'
                      }`}
                    >
                      2
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Split into PT + YT</p>
                      <p className="mt-1">
                        For each token deposited, you receive 1 Principal Token (PT) and 1 Yield
                        Token (YT).
                      </p>
                    </div>
                  </div>
                  <div className="flex gap-3">
                    <div className="bg-primary/20 text-primary flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-medium">
                      3
                    </div>
                    <div>
                      <p className="text-foreground font-medium">Use Your Tokens</p>
                      <p className="mt-1">
                        PT can be traded or held until maturity. YT earns yield until expiry.
                      </p>
                    </div>
                  </div>
                </div>
              )}

              <div className="bg-muted mt-6 rounded-lg p-4">
                <h3 className="text-foreground text-sm font-medium">Token Details</h3>
                <dl className="mt-2 space-y-2 text-sm">
                  <div className="flex justify-between">
                    <dt className="text-muted-foreground">PT (Principal Token)</dt>
                    <dd className="text-foreground">Redeemable for underlying at maturity</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="text-muted-foreground">YT (Yield Token)</dt>
                    <dd className="text-foreground">Earns yield until expiry</dd>
                  </div>
                </dl>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function MintPageContent(): ReactNode {
  const { isSimple } = useUIMode();

  return isSimple ? <SimpleModeContent /> : <AdvancedModeContent />;
}

export default function MintPage(): ReactNode {
  const { isSimple } = useUIMode();

  return (
    <div className="mx-auto max-w-7xl px-4 py-12">
      {/* Header */}
      <div className="mb-8">
        <Link
          href="/"
          className="text-muted-foreground hover:text-foreground mb-4 inline-flex items-center gap-1 text-sm"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M15 19l-7-7 7-7"
            />
          </svg>
          Back to {isSimple ? 'Markets' : 'Dashboard'}
        </Link>
        <h1 className="text-foreground text-3xl font-bold">
          {isSimple ? 'Earn Fixed Yield' : 'Deposit & Split'}
        </h1>
        <p className="text-muted-foreground mt-2">
          {isSimple
            ? 'Deposit tokens to earn a guaranteed fixed rate'
            : 'Deposit yield-bearing tokens, then split into Principal Tokens (PT) and Yield Tokens (YT)'}
        </p>
      </div>

      {/* Content wrapped in Suspense for useSearchParams */}
      <Suspense fallback={<SkeletonCard className="h-[500px] max-w-lg" />}>
        <MintPageContent />
      </Suspense>
    </div>
  );
}
