// packages/frontend-solid/src/shared/ui/Toast.tsx
import { Toast } from '@kobalte/core/toast';
import { cn } from '@shared/lib/utils';
import { cva, type VariantProps } from 'class-variance-authority';
import { type ComponentProps, type JSX, Match, Switch, splitProps } from 'solid-js';

/** Inline SVG X icon for close button */
function XIcon(props: JSX.SvgSVGAttributes<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}

/** Inline SVG success checkmark icon */
function CircleCheckIcon(props: JSX.SvgSVGAttributes<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}

/** Inline SVG info icon */
function InfoIcon(props: JSX.SvgSVGAttributes<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...props}
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 16v-4" />
      <path d="M12 8h.01" />
    </svg>
  );
}

/** Inline SVG warning triangle icon */
function TriangleAlertIcon(props: JSX.SvgSVGAttributes<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3" />
      <path d="M12 9v4" />
      <path d="M12 17h.01" />
    </svg>
  );
}

/** Inline SVG error octagon X icon */
function OctagonXIcon(props: JSX.SvgSVGAttributes<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M2.586 16.726A2 2 0 0 1 2 15.312V8.688a2 2 0 0 1 .586-1.414l4.688-4.688A2 2 0 0 1 8.688 2h6.624a2 2 0 0 1 1.414.586l4.688 4.688A2 2 0 0 1 22 8.688v6.624a2 2 0 0 1-.586 1.414l-4.688 4.688a2 2 0 0 1-1.414.586H8.688a2 2 0 0 1-1.414-.586z" />
      <path d="m15 9-6 6" />
      <path d="m9 9 6 6" />
    </svg>
  );
}

/** Inline SVG spinner for loading state */
function Loader2Icon(props: JSX.SvgSVGAttributes<SVGSVGElement>) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      aria-hidden="true"
      {...props}
    >
      <path d="M21 12a9 9 0 1 1-6.219-8.56" />
    </svg>
  );
}

const toastVariants = cva(
  [
    // Base styles
    'group pointer-events-auto relative flex w-full items-center justify-between gap-4 overflow-hidden rounded-xl border p-4 shadow-lg transition-all',
    // Animation classes using Kobalte's data-state attributes
    'data-[state=open]:animate-in data-[state=closed]:animate-out',
    'data-[swipe=end]:animate-out data-[state=closed]:fade-out-80',
    'data-[state=closed]:slide-out-to-right-full data-[state=open]:slide-in-from-top-full',
    'data-[state=open]:sm:slide-in-from-bottom-full',
  ].join(' '),
  {
    variants: {
      variant: {
        default: 'border-border bg-background text-foreground',
        success: 'border-success/50 bg-success/10 text-success-foreground',
        error: 'border-destructive/50 bg-destructive/10 text-destructive',
        warning: 'border-warning/50 bg-warning/10 text-warning-foreground',
        info: 'border-info/50 bg-info/10 text-info-foreground',
        loading: 'border-border bg-background text-foreground',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);

type ToastVariant = 'default' | 'success' | 'error' | 'warning' | 'info' | 'loading';

type ToastRootProps = ComponentProps<typeof Toast> &
  VariantProps<typeof toastVariants> & {
    variant?: ToastVariant;
  };

/**
 * Toast root component that wraps Kobalte Toast primitive.
 *
 * Features:
 * - Multiple variants (default, success, error, warning, info, loading)
 * - Accessible with WAI-ARIA Toast pattern
 * - Swipe to dismiss
 * - Auto-dismiss with configurable duration
 */
function ToastRoot(props: ToastRootProps): JSX.Element {
  const [local, others] = splitProps(props, ['class', 'variant']);

  return (
    <Toast
      data-slot="toast"
      class={cn(toastVariants({ variant: local.variant }), local.class)}
      {...others}
    />
  );
}

type ToastTitleProps = ComponentProps<typeof Toast.Title>;

function ToastTitle(props: ToastTitleProps): JSX.Element {
  const [local, others] = splitProps(props, ['class']);

  return (
    <Toast.Title
      data-slot="toast-title"
      class={cn('text-sm font-semibold', local.class)}
      {...others}
    />
  );
}

type ToastDescriptionProps = ComponentProps<typeof Toast.Description>;

function ToastDescription(props: ToastDescriptionProps): JSX.Element {
  const [local, others] = splitProps(props, ['class']);

  return (
    <Toast.Description
      data-slot="toast-description"
      class={cn('text-sm opacity-90', local.class)}
      {...others}
    />
  );
}

type ToastCloseButtonProps = ComponentProps<typeof Toast.CloseButton>;

function ToastCloseButton(props: ToastCloseButtonProps): JSX.Element {
  const [local, others] = splitProps(props, ['class']);

  return (
    <Toast.CloseButton
      data-slot="toast-close"
      class={cn(
        'absolute right-2 top-2 rounded-md p-1 opacity-0 transition-opacity',
        'hover:opacity-100 group-hover:opacity-100',
        'focus:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring',
        local.class
      )}
      {...others}
    >
      <XIcon class="size-4" />
      <span class="sr-only">Close</span>
    </Toast.CloseButton>
  );
}

type ToastProgressFillProps = ComponentProps<typeof Toast.ProgressFill>;

function ToastProgressFill(props: ToastProgressFillProps): JSX.Element {
  const [local, others] = splitProps(props, ['class']);

  return (
    <Toast.ProgressFill
      data-slot="toast-progress"
      class={cn(
        'bg-primary h-full w-[var(--kb-toast-progress-fill-width)] transition-all',
        local.class
      )}
      {...others}
    />
  );
}

type ToastProgressTrackProps = ComponentProps<typeof Toast.ProgressTrack>;

function ToastProgressTrack(props: ToastProgressTrackProps): JSX.Element {
  const [local, others] = splitProps(props, ['class', 'children']);

  return (
    <Toast.ProgressTrack
      data-slot="toast-progress-track"
      class={cn('absolute bottom-0 left-0 right-0 h-1 overflow-hidden bg-muted', local.class)}
      {...others}
    >
      {local.children}
    </Toast.ProgressTrack>
  );
}

/** Toast icon component based on variant */
function ToastIcon(props: { variant?: ToastVariant; class?: string }): JSX.Element {
  const iconClass = () => cn('size-4 shrink-0', props.class);

  return (
    <Switch>
      <Match when={props.variant === 'success'}>
        <CircleCheckIcon class={cn(iconClass(), 'text-success')} />
      </Match>
      <Match when={props.variant === 'error'}>
        <OctagonXIcon class={cn(iconClass(), 'text-destructive')} />
      </Match>
      <Match when={props.variant === 'warning'}>
        <TriangleAlertIcon class={cn(iconClass(), 'text-warning')} />
      </Match>
      <Match when={props.variant === 'info'}>
        <InfoIcon class={cn(iconClass(), 'text-info')} />
      </Match>
      <Match when={props.variant === 'loading'}>
        <Loader2Icon class={cn(iconClass(), 'animate-spin')} />
      </Match>
    </Switch>
  );
}

// Re-export Toast primitive for advanced usage
export { Toast };

// Export wrapper components
export {
  ToastRoot,
  ToastTitle,
  ToastDescription,
  ToastCloseButton,
  ToastProgressFill,
  ToastProgressTrack,
  ToastIcon,
  toastVariants,
};

export type {
  ToastRootProps,
  ToastTitleProps,
  ToastDescriptionProps,
  ToastCloseButtonProps,
  ToastProgressFillProps,
  ToastProgressTrackProps,
  ToastVariant,
};

// Export icons for external use
export { CircleCheckIcon, InfoIcon, TriangleAlertIcon, OctagonXIcon, Loader2Icon };

// packages/frontend/src/components/ui/Toast.tsx
'use client';

import * as ToastPrimitive from '@radix-ui/react-toast';
import { type VariantProps, cva } from 'class-variance-authority';
import { forwardRef, type ReactNode } from 'react';

import { cn } from '@/lib/utils';

const toastVariants = cva(
  'group pointer-events-auto relative flex w-full items-center justify-between space-x-4 overflow-hidden rounded-lg border p-4 shadow-lg transition-all data-[swipe=cancel]:translate-x-0 data-[swipe=end]:translate-x-[var(--radix-toast-swipe-end-x)] data-[swipe=move]:translate-x-[var(--radix-toast-swipe-move-x)] data-[swipe=move]:transition-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[swipe=end]:animate-out data-[state=closed]:fade-out-80 data-[state=closed]:slide-out-to-right-full data-[state=open]:slide-in-from-top-full',
  {
    variants: {
      variant: {
        default: 'border-neutral-800 bg-neutral-900 text-neutral-100',
        success: 'border-green-800 bg-green-950 text-green-100',
        error: 'border-red-800 bg-red-950 text-red-100',
        warning: 'border-yellow-800 bg-yellow-950 text-yellow-100',
      },
    },
    defaultVariants: {
      variant: 'default',
    },
  }
);

export interface ToastProps
  extends
    React.ComponentPropsWithoutRef<typeof ToastPrimitive.Root>,
    VariantProps<typeof toastVariants> {}

export const Toast = forwardRef<React.ComponentRef<typeof ToastPrimitive.Root>, ToastProps>(
  ({ className, variant, ...props }, ref) => {
    return (
      <ToastPrimitive.Root
        ref={ref}
        className={cn(toastVariants({ variant }), className)}
        {...props}
      />
    );
  }
);
Toast.displayName = 'Toast';

export const ToastViewport = forwardRef<
  React.ComponentRef<typeof ToastPrimitive.Viewport>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitive.Viewport>
>(({ className, ...props }, ref) => (
  <ToastPrimitive.Viewport
    ref={ref}
    className={cn(
      'fixed top-0 z-[100] flex max-h-screen w-full flex-col-reverse p-4 sm:bottom-0 sm:right-0 sm:top-auto sm:flex-col md:max-w-[420px]',
      className
    )}
    {...props}
  />
));
ToastViewport.displayName = 'ToastViewport';

export const ToastTitle = forwardRef<
  React.ComponentRef<typeof ToastPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitive.Title>
>(({ className, ...props }, ref) => (
  <ToastPrimitive.Title ref={ref} className={cn('text-sm font-semibold', className)} {...props} />
));
ToastTitle.displayName = 'ToastTitle';

export const ToastDescription = forwardRef<
  React.ComponentRef<typeof ToastPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitive.Description>
>(({ className, ...props }, ref) => (
  <ToastPrimitive.Description
    ref={ref}
    className={cn('text-sm opacity-90', className)}
    {...props}
  />
));
ToastDescription.displayName = 'ToastDescription';

export const ToastClose = forwardRef<
  React.ComponentRef<typeof ToastPrimitive.Close>,
  React.ComponentPropsWithoutRef<typeof ToastPrimitive.Close>
>(({ className, ...props }, ref) => (
  <ToastPrimitive.Close
    ref={ref}
    className={cn(
      'absolute right-2 top-2 rounded-md p-1 opacity-0 transition-opacity hover:opacity-100 focus:opacity-100 focus:outline-none focus:ring-2 focus:ring-accent group-hover:opacity-100',
      className
    )}
    toast-close=""
    {...props}
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="18" y1="6" x2="6" y2="18" />
      <line x1="6" y1="6" x2="18" y2="18" />
    </svg>
  </ToastPrimitive.Close>
));
ToastClose.displayName = 'ToastClose';

export function ToastProvider({ children }: { children: ReactNode }): ReactNode {
  return <ToastPrimitive.Provider>{children}</ToastPrimitive.Provider>;
}
