// packages/frontend-solid/src/routes/faucet.tsx
import { createMemo, createSignal, type JSX, Show } from 'solid-js';
import { Contract, type Call } from 'starknet';

import { useAccount, useStarknet } from '@/features/wallet';
import { getFaucetInfo } from '@/shared/config/addresses';
import { fromWad } from '@/shared/math/wad';
import { getExplorerTxUrl } from '@/shared/starknet/provider';
import { Button } from '@/shared/ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/shared/ui/Card';

// Simple Faucet ABI - only the functions we need
const FAUCET_ABI = [
  {
    type: 'function',
    name: 'mint',
    inputs: [],
    outputs: [],
    state_mutability: 'external',
  },
  {
    type: 'function',
    name: 'can_mint',
    inputs: [{ name: 'account', type: 'core::starknet::contract_address::ContractAddress' }],
    outputs: [{ type: 'core::bool' }],
    state_mutability: 'view',
  },
  {
    type: 'function',
    name: 'mint_amount',
    inputs: [],
    outputs: [{ type: 'core::integer::u256' }],
    state_mutability: 'view',
  },
  {
    type: 'function',
    name: 'is_paused',
    inputs: [],
    outputs: [{ type: 'core::bool' }],
    state_mutability: 'view',
  },
] as const;

/**
 * Faucet page - Get test tokens for the protocol
 *
 * Features:
 * - Display faucet info (token, amount, daily limit)
 * - Mint test tokens with one click
 * - Show mint status and cooldown
 */
export default function FaucetPage(): JSX.Element {
  const { network } = useStarknet();
  const { account, isConnected } = useAccount();

  const [isMinting, setIsMinting] = createSignal(false);
  const [mintError, setMintError] = createSignal<string | null>(null);
  const [mintSuccess, setMintSuccess] = createSignal(false);
  const [txHash, setTxHash] = createSignal<string | null>(null);

  // Get faucet info for current network
  const faucetInfo = createMemo(() => getFaucetInfo(network));

  // Format the daily limit for display
  const formattedDailyLimit = createMemo(() => {
    const info = faucetInfo();
    if (!info) return '0';
    const limit = fromWad(BigInt(info.dailyLimit));
    return limit.toFixed(0);
  });

  // Handle mint action
  const handleMint = async (): Promise<void> => {
    const currentAccount = account();
    const info = faucetInfo();

    if (!currentAccount || !info) {
      setMintError('Wallet not connected or faucet not available');
      return;
    }

    setIsMinting(true);
    setMintError(null);
    setMintSuccess(false);
    setTxHash(null);

    try {
      // Create faucet contract instance
      const faucetContract = new Contract({
        abi: FAUCET_ABI,
        address: info.faucetAddress,
        providerOrAccount: currentAccount,
      });

      // Build the mint call
      const mintCall: Call = faucetContract.populate('mint', []);

      // Execute the transaction
      const result = await currentAccount.execute([mintCall]);

      setTxHash(result.transaction_hash);
      setMintSuccess(true);
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';

      // Parse common error messages
      if (errorMessage.includes('already minted today')) {
        setMintError('You have already claimed tokens today. Please try again tomorrow.');
      } else if (errorMessage.includes('paused')) {
        setMintError('The faucet is currently paused. Please try again later.');
      } else if (errorMessage.includes('User abort') || errorMessage.includes('rejected')) {
        setMintError('Transaction was cancelled.');
      } else {
        setMintError(`Failed to mint: ${errorMessage}`);
      }
    } finally {
      setIsMinting(false);
    }
  };

  return (
    <div class="mx-auto max-w-2xl px-4 py-8">
      {/* Page Header */}
      <div class="mb-8 text-center">
        <h1 class="text-foreground text-3xl font-semibold">Token Faucet</h1>
        <p class="text-muted-foreground mt-2">
          Get free test tokens to explore the Horizon Protocol.
        </p>
      </div>

      {/* Faucet Not Available */}
      <Show when={!faucetInfo()}>
        <Card>
          <CardContent class="py-8 text-center">
            <div class="text-muted-foreground mx-auto mb-4 h-12 w-12">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="48"
                height="48"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              >
                <circle cx="12" cy="12" r="10" />
                <path d="M12 16v-4" />
                <path d="M12 8h.01" />
              </svg>
            </div>
            <h3 class="text-foreground text-lg font-medium">Faucet Not Available</h3>
            <p class="text-muted-foreground mt-2 text-sm">
              The faucet is only available on Starknet Mainnet. Please connect to Mainnet to claim
              test tokens.
            </p>
          </CardContent>
        </Card>
      </Show>

      {/* Faucet Available */}
      <Show when={faucetInfo()}>
        {(info) => (
          <div class="space-y-6">
            {/* Faucet Card */}
            <Card>
              <CardHeader>
                <CardTitle>Claim {info().tokenSymbol}</CardTitle>
                <CardDescription>
                  Get free {info().tokenName} tokens to test the protocol.
                </CardDescription>
              </CardHeader>
              <CardContent class="space-y-6">
                {/* Token Info */}
                <div class="bg-muted/30 rounded-lg p-4">
                  <div class="space-y-3">
                    <div class="flex items-center justify-between">
                      <span class="text-muted-foreground text-sm">Token</span>
                      <span class="font-medium">{info().tokenSymbol}</span>
                    </div>
                    <div class="flex items-center justify-between">
                      <span class="text-muted-foreground text-sm">Amount per Claim</span>
                      <span class="font-mono font-medium">{formattedDailyLimit()} tokens</span>
                    </div>
                    <div class="flex items-center justify-between">
                      <span class="text-muted-foreground text-sm">Cooldown</span>
                      <span class="text-sm">24 hours</span>
                    </div>
                  </div>
                </div>

                {/* Not Connected State */}
                <Show when={!isConnected()}>
                  <div class="bg-warning/10 border-warning/20 rounded-lg border p-4 text-center">
                    <p class="text-warning-foreground text-sm">
                      Connect your wallet to claim test tokens.
                    </p>
                  </div>
                </Show>

                {/* Connected State */}
                <Show when={isConnected()}>
                  <div class="space-y-4">
                    {/* Error Message */}
                    <Show when={mintError()}>
                      <div class="bg-destructive/10 border-destructive/20 rounded-lg border p-4">
                        <p class="text-destructive text-sm">{mintError()}</p>
                      </div>
                    </Show>

                    {/* Success Message */}
                    <Show when={mintSuccess()}>
                      <div class="bg-success/10 border-success/20 rounded-lg border p-4">
                        <p class="text-success text-sm">
                          Successfully claimed {formattedDailyLimit()} {info().tokenSymbol}!
                        </p>
                        <Show when={txHash()}>
                          {(hash) => {
                            const explorerUrl = getExplorerTxUrl(hash(), network);
                            return (
                              <Show when={explorerUrl}>
                                <a
                                  href={explorerUrl}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  class="text-success/80 hover:text-success mt-2 inline-flex items-center gap-1 text-xs underline"
                                >
                                  View transaction
                                  <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    width="12"
                                    height="12"
                                    viewBox="0 0 24 24"
                                    fill="none"
                                    stroke="currentColor"
                                    stroke-width="2"
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                  >
                                    <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6" />
                                    <polyline points="15 3 21 3 21 9" />
                                    <line x1="10" y1="14" x2="21" y2="3" />
                                  </svg>
                                </a>
                              </Show>
                            );
                          }}
                        </Show>
                      </div>
                    </Show>

                    {/* Mint Button */}
                    <Button
                      class="w-full"
                      size="lg"
                      onClick={() => void handleMint()}
                      loading={isMinting()}
                      loadingText="Claiming..."
                    >
                      Claim {formattedDailyLimit()} {info().tokenSymbol}
                    </Button>
                  </div>
                </Show>
              </CardContent>
            </Card>

            {/* Info Card */}
            <Card>
              <CardHeader>
                <CardTitle class="text-lg">About Test Tokens</CardTitle>
              </CardHeader>
              <CardContent>
                <div class="text-muted-foreground space-y-3 text-sm">
                  <p>
                    <strong>{info().tokenSymbol}</strong> is a mock yield-bearing token used for
                    testing the Horizon Protocol on mainnet. These tokens have no real value.
                  </p>
                  <p>
                    Each wallet can claim <strong>{formattedDailyLimit()} tokens per day</strong>.
                    Use these tokens to:
                  </p>
                  <ul class="list-inside list-disc space-y-1 pl-2">
                    <li>Mint PT and YT tokens</li>
                    <li>Trade on the PT/SY market</li>
                    <li>Provide liquidity to pools</li>
                    <li>Test yield strategies</li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </Show>
    </div>
  );
}

// packages/frontend/src/app/faucet/page.tsx
'use client';

import { AlertTriangle, Check, Copy, Droplets, ExternalLink, Loader2 } from 'lucide-react';
import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import type { Call } from 'starknet';

import { useStarknet } from '@features/wallet';
import { getFaucetInfo } from '@shared/config/addresses';
import { useTransaction } from '@shared/hooks/useTransaction';
import { logError } from '@shared/server/logger';
import { getFaucetContract } from '@shared/starknet/contracts';
import { Button } from '@shared/ui/Button';
import { Input } from '@shared/ui/Input';
import { Separator } from '@shared/ui/separator';

export default function FaucetPage(): React.ReactNode {
  const { address, isConnected, provider, network } = useStarknet();
  const { execute, status, reset } = useTransaction();
  const [inputAddress, setInputAddress] = useState('');
  const [canMint, setCanMint] = useState<boolean | null>(null);
  const [isChecking, setIsChecking] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const faucetInfo = getFaucetInfo(network);
  const targetAddress = isConnected && address ? address : inputAddress;
  const isMinting = status === 'signing' || status === 'pending';
  const mintSuccess = status === 'success';

  // Check if address can mint
  const checkCanMint = useCallback(async () => {
    if (!faucetInfo || !targetAddress) {
      setCanMint(null);
      return;
    }

    setIsChecking(true);
    setError(null);

    try {
      const faucet = getFaucetContract(faucetInfo.faucetAddress, provider);
      const result = await faucet.can_mint(targetAddress);
      setCanMint(result);
    } catch (err) {
      logError(err, { module: 'faucet', action: 'checkCanMint', targetAddress });
      setError('Failed to check mint status');
      setCanMint(null);
    } finally {
      setIsChecking(false);
    }
  }, [faucetInfo, targetAddress, provider]);

  // Check on mount and when address changes
  useEffect(() => {
    if (targetAddress) {
      void checkCanMint();
    }
  }, [targetAddress, checkCanMint]);

  // Reset on success and recheck
  useEffect(() => {
    if (mintSuccess) {
      setCanMint(false);
    }
  }, [mintSuccess]);

  // Handle mint
  const handleMint = async (): Promise<void> => {
    if (!faucetInfo || !isConnected) {
      setError('Please connect your wallet first');
      return;
    }

    setError(null);
    reset();

    try {
      const mintCall: Call = {
        contractAddress: faucetInfo.faucetAddress,
        entrypoint: 'mint',
        calldata: [],
      };

      await execute(mintCall);
    } catch (err) {
      logError(err, { module: 'faucet', action: 'mint' });
      const errorMessage = err instanceof Error ? err.message : 'Failed to mint tokens';
      if (errorMessage.includes('already minted')) {
        setError('You have already minted today. Please try again in 24 hours.');
      } else {
        setError(errorMessage);
      }
    }
  };

  // Copy token address
  const copyTokenAddress = (): void => {
    if (faucetInfo) {
      void navigator.clipboard.writeText(faucetInfo.tokenAddress);
      setCopied(true);
      setTimeout(() => {
        setCopied(false);
      }, 2000);
    }
  };

  // If faucet not available on this network
  if (!faucetInfo) {
    return (
      <div className="mx-auto max-w-lg px-4 py-12">
        <div className="border-border bg-card rounded-lg border p-8 text-center">
          <AlertTriangle className="text-warning mx-auto h-12 w-12" />
          <h1 className="text-foreground mt-4 text-xl font-bold">Faucet Not Available</h1>
          <p className="text-muted-foreground mt-2">
            The faucet is only available on Starknet mainnet for testing purposes.
          </p>
          <Link href="/">
            <Button className="mt-6">Go to App</Button>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-lg px-4 py-12">
      {/* Back link */}
      <Link
        href="/"
        className="text-muted-foreground hover:text-foreground mb-8 inline-flex items-center gap-1 text-sm"
      >
        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
        </svg>
        Back to App
      </Link>

      {/* Header */}
      <div className="mb-8 text-center">
        <div className="bg-primary/10 mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full">
          <Droplets className="text-primary h-8 w-8" />
        </div>
        <h1 className="text-foreground text-2xl font-bold">Test Token Faucet</h1>
        <p className="text-muted-foreground mt-2">
          Get free hrzSTRK tokens to test Horizon Protocol
        </p>
      </div>

      {/* Main Card */}
      <div className="border-border bg-card rounded-lg border p-6">
        {/* Token Info */}
        <div className="bg-muted/50 rounded-lg p-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-foreground font-medium">You will receive</p>
              <p className="text-primary text-2xl font-bold">100 {faucetInfo.tokenSymbol}</p>
            </div>
            <div className="text-muted-foreground text-right text-sm">
              <p>Once per 24 hours</p>
            </div>
          </div>
        </div>

        <Separator className="my-6" />

        {/* Token Address */}
        <div>
          <label className="text-foreground mb-2 block text-sm font-medium">
            Token Contract Address
          </label>
          <p className="text-muted-foreground mb-2 text-xs">
            Add this token to your wallet to see your balance
          </p>
          <div className="flex gap-2">
            <Input
              value={faucetInfo.tokenAddress}
              readOnly
              className="bg-muted font-mono text-xs"
            />
            <Button variant="outline" size="icon" onClick={copyTokenAddress}>
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            </Button>
          </div>
        </div>

        <Separator className="my-6" />

        {/* Wallet Address */}
        <div>
          <label className="text-foreground mb-2 block text-sm font-medium">Your Wallet</label>
          {isConnected && address ? (
            <Input value={address} readOnly className="bg-muted font-mono text-xs" />
          ) : (
            <div className="space-y-2">
              <Input
                value={inputAddress}
                onChange={(e) => {
                  setInputAddress(e.target.value);
                }}
                placeholder="0x..."
                className="font-mono text-xs"
              />
              <p className="text-muted-foreground text-xs">
                Connect your wallet or enter an address to check eligibility
              </p>
            </div>
          )}
        </div>

        {/* Status */}
        {targetAddress && (
          <div className="mt-6">
            {isChecking ? (
              <div className="text-muted-foreground flex items-center gap-2 text-sm">
                <Loader2 className="h-4 w-4 animate-spin" />
                Checking eligibility...
              </div>
            ) : canMint === false ? (
              <div className="border-warning/20 bg-warning/5 rounded-lg border p-4">
                <div className="flex items-start gap-3">
                  <AlertTriangle className="text-warning mt-0.5 h-5 w-5 flex-shrink-0" />
                  <div>
                    <p className="text-foreground font-medium">Already minted today</p>
                    <p className="text-muted-foreground mt-1 text-sm">
                      You can only mint once every 24 hours. Please try again later.
                    </p>
                  </div>
                </div>
              </div>
            ) : canMint === true ? (
              <div className="border-primary/20 bg-primary/5 rounded-lg border p-4">
                <div className="flex items-start gap-3">
                  <Check className="text-primary mt-0.5 h-5 w-5 flex-shrink-0" />
                  <div>
                    <p className="text-foreground font-medium">Eligible to mint</p>
                    <p className="text-muted-foreground mt-1 text-sm">
                      You can claim your 100 {faucetInfo.tokenSymbol} test tokens.
                    </p>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        )}

        {/* Error */}
        {error && (
          <div className="border-destructive/20 bg-destructive/5 mt-4 rounded-lg border p-4">
            <p className="text-destructive text-sm">{error}</p>
          </div>
        )}

        {/* Success */}
        {mintSuccess && (
          <div className="border-primary/20 bg-primary/5 mt-4 rounded-lg border p-4">
            <div className="flex items-start gap-3">
              <Check className="text-primary mt-0.5 h-5 w-5 flex-shrink-0" />
              <div>
                <p className="text-foreground font-medium">Tokens minted successfully!</p>
                <p className="text-muted-foreground mt-1 text-sm">
                  100 {faucetInfo.tokenSymbol} have been sent to your wallet.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Mint Button */}
        <div className="mt-6">
          {isConnected ? (
            <Button
              onClick={() => void handleMint()}
              disabled={isMinting || canMint === false || !canMint}
              className="w-full"
            >
              {isMinting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Minting...
                </>
              ) : (
                <>
                  <Droplets className="mr-2 h-4 w-4" />
                  Mint 100 {faucetInfo.tokenSymbol}
                </>
              )}
            </Button>
          ) : (
            <p className="text-muted-foreground text-center text-sm">
              Connect your wallet to mint tokens
            </p>
          )}
        </div>
      </div>

      {/* Info */}
      <div className="mt-6 space-y-3 text-center">
        <p className="text-muted-foreground text-sm">
          These are test tokens with no real value. Use them to explore Horizon Protocol.
        </p>
        <Link
          href="/docs/getting-started"
          className="text-primary hover:text-primary/80 inline-flex items-center gap-1 text-sm"
        >
          Learn how to use Horizon
          <ExternalLink className="h-3.5 w-3.5" />
        </Link>
      </div>
    </div>
  );
}
