// packages/frontend-solid/src/shared/ui/HoverCard.tsx
import { HoverCard as HoverCardPrimitive } from '@kobalte/core/hover-card';
import { cn } from '@shared/lib/utils';
import { type ComponentProps, type JSX, splitProps } from 'solid-js';

type HoverCardRootProps = ComponentProps<typeof HoverCardPrimitive>;

/**
 * HoverCard root component that contains all hover card parts.
 *
 * Uses Kobalte HoverCard primitive for showing content on hover.
 * - Delayed open/close for better UX
 * - Accessible tooltip alternative for rich content
 */
function HoverCard(props: HoverCardRootProps): JSX.Element {
  return <HoverCardPrimitive data-slot="hover-card" {...props} />;
}

type HoverCardTriggerProps = ComponentProps<typeof HoverCardPrimitive.Trigger>;

function HoverCardTrigger(props: HoverCardTriggerProps): JSX.Element {
  return <HoverCardPrimitive.Trigger data-slot="hover-card-trigger" {...props} />;
}

type HoverCardPortalProps = ComponentProps<typeof HoverCardPrimitive.Portal>;

function HoverCardPortal(props: HoverCardPortalProps): JSX.Element {
  return <HoverCardPrimitive.Portal data-slot="hover-card-portal" {...props} />;
}

type HoverCardContentProps = ComponentProps<typeof HoverCardPrimitive.Content>;

function HoverCardContent(props: HoverCardContentProps): JSX.Element {
  const [local, others] = splitProps(props, ['class']);

  return (
    <HoverCardPrimitive.Portal>
      <HoverCardPrimitive.Content
        data-slot="hover-card-content"
        class={cn(
          'data-[expanded]:animate-in data-[closed]:animate-out data-[closed]:fade-out-0 data-[expanded]:fade-in-0 data-[closed]:zoom-out-95 data-[expanded]:zoom-in-95 ring-foreground/5 bg-popover text-popover-foreground z-[100] w-72 rounded-2xl p-4 text-sm shadow-2xl ring-1 outline-hidden duration-100',
          local.class
        )}
        {...others}
      />
    </HoverCardPrimitive.Portal>
  );
}

type HoverCardArrowProps = ComponentProps<typeof HoverCardPrimitive.Arrow>;

function HoverCardArrow(props: HoverCardArrowProps): JSX.Element {
  const [local, others] = splitProps(props, ['class']);

  return (
    <HoverCardPrimitive.Arrow
      data-slot="hover-card-arrow"
      class={cn('fill-popover', local.class)}
      {...others}
    />
  );
}

// Export Kobalte primitive for direct access
export { HoverCardPrimitive };

export { HoverCard, HoverCardTrigger, HoverCardPortal, HoverCardContent, HoverCardArrow };
export type {
  HoverCardRootProps,
  HoverCardTriggerProps,
  HoverCardPortalProps,
  HoverCardContentProps,
  HoverCardArrowProps,
};

// packages/frontend/src/shared/ui/hover-card.tsx
'use client';

import { PreviewCard as PreviewCardPrimitive } from '@base-ui/react/preview-card';
import type { ReactNode } from 'react';

import { cn } from '@shared/lib/utils';

function HoverCard({ ...props }: PreviewCardPrimitive.Root.Props): ReactNode {
  return <PreviewCardPrimitive.Root data-slot="hover-card" {...props} />;
}

function HoverCardTrigger({ ...props }: PreviewCardPrimitive.Trigger.Props): ReactNode {
  return <PreviewCardPrimitive.Trigger data-slot="hover-card-trigger" {...props} />;
}

function HoverCardContent({
  className,
  side = 'bottom',
  sideOffset = 8,
  align = 'center',
  alignOffset = 0,
  ...props
}: PreviewCardPrimitive.Popup.Props &
  Pick<
    PreviewCardPrimitive.Positioner.Props,
    'align' | 'alignOffset' | 'side' | 'sideOffset'
  >): ReactNode {
  return (
    <PreviewCardPrimitive.Portal data-slot="hover-card-portal">
      <PreviewCardPrimitive.Positioner
        align={align}
        alignOffset={alignOffset}
        side={side}
        sideOffset={sideOffset}
        className="isolate z-[100]"
      >
        <PreviewCardPrimitive.Popup
          data-slot="hover-card-content"
          className={cn(
            'data-open:animate-in data-closed:animate-out data-closed:fade-out-0 data-open:fade-in-0 data-closed:zoom-out-95 data-open:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 ring-foreground/5 bg-popover text-popover-foreground z-[100] w-72 origin-(--transform-origin) rounded-2xl p-4 text-sm shadow-2xl ring-1 outline-hidden duration-100',
            className
          )}
          {...props}
        />
      </PreviewCardPrimitive.Positioner>
    </PreviewCardPrimitive.Portal>
  );
}

export { HoverCard, HoverCardTrigger, HoverCardContent };
