// packages/frontend-solid/src/features/swap/ui/SwapForm.tsx
import { type Accessor, createEffect, createMemo, createSignal, on, type JSX, Show } from 'solid-js';

import { type MarketData } from '@/features/markets';
import { useAccount, useStarknet } from '@/features/wallet';
import { getAddresses, getMarketParams } from '@shared/config/addresses';
import { cn } from '@shared/lib/utils';
import { type MarketState as AmmMarketState, getImpliedApy } from '@shared/math/amm';
import { formatWad, fromWad, parseWad } from '@shared/math/wad';
import { createAnimatedNumber } from '@shared/ui/AnimatedNumber';
import { Button } from '@shared/ui/Button';
import {
  FormActions,
  FormDivider,
  FormInputSection,
  FormLayout,
  FormOutputSection,
  FormRow,
} from '@shared/ui/FormLayout';
import { NumberInput } from '@shared/ui/Input';
import { NearExpiryWarning } from '@shared/ui/NearExpiryWarning';
import { ToggleGroup, ToggleGroupItem } from '@shared/ui/ToggleGroup';
import { toast } from '@shared/ui/Toaster';

import {
  calculateSwapQuote,
  deriveButtonState,
  deriveOutputBadgeStyle,
  deriveSwapDirection,
  deriveSwapFormUiState,
  deriveTokenLabels,
  getInputTokenAddress,
  getTokenTypeDescription,
  isValidBuySell,
  isValidTokenType,
  type TokenType,
} from '../lib/swapFormLogic';
import { calculateMinOutput, type SwapDirection, useSwap } from '../model/useSwap';

export interface SwapFormProps {
  market: MarketData;
  class?: string;
}

const SLIPPAGE_OPTIONS = [
  { label: '0.1%', value: 10 },
  { label: '0.5%', value: 50 },
  { label: '1%', value: 100 },
];

/**
 * Inline ArrowUpDown icon to avoid lucide-solid dependency
 */
function ArrowUpDownIcon(props: JSX.SvgSVGAttributes<SVGSVGElement>): JSX.Element {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
      {...props}
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>
  );
}

/**
 * SwapForm - SolidJS port with reactive state management
 *
 * Features:
 * - Inline token type + direction toggles
 * - Visual direction indicator with animated swap button
 * - Price impact display
 * - Slippage settings
 * - Directional background gradient
 */
export function SwapForm(props: SwapFormProps): JSX.Element {
  const { isConnected, network } = useStarknet();
  const { address } = useAccount();
  const addresses = () => getAddresses(network);

  // Form state signals
  const [tokenType, setTokenType] = createSignal<TokenType>('PT');
  const [isBuying, setIsBuying] = createSignal(true);
  const [inputAmount, setInputAmount] = createSignal('');
  const [isFlipping, setIsFlipping] = createSignal(false);
  const [slippageBps, setSlippageBps] = createSignal(50); // 0.5% default

  // Derive swap direction from token type and buy/sell (lookup table)
  const direction = createMemo(() => deriveSwapDirection(tokenType(), isBuying()));

  const {
    swap,
    isSwapping,
    isSuccess,
    isError,
    error,
    transactionHash,
    reset: resetSwap,
  } = useSwap();

  // Derive token labels and addresses using pure functions
  const tokenSymbol = () => props.market.metadata?.yieldTokenSymbol ?? 'Token';
  const tokenLabels = createMemo(() => deriveTokenLabels(tokenSymbol(), tokenType(), isBuying()));
  const inputToken = createMemo(() => getInputTokenAddress(props.market, tokenType(), isBuying()));
  const inputLabel = () => tokenLabels().input;
  const outputLabel = () => tokenLabels().output;
  const syLabel = () => tokenLabels().sy;

  // Get market params for AMM calculations
  const marketParams = createMemo(() => getMarketParams(network));

  // Parse input amount and validate
  const parsedInputAmount = createMemo(() => {
    const amount = inputAmount();
    if (!amount || amount === '') return BigInt(0);
    try {
      return parseWad(amount);
    } catch {
      return BigInt(0);
    }
  });
  const isValidAmount = createMemo(() => parsedInputAmount() > 0n);

  // Build AMM market state for accurate calculations
  const ammState = createMemo((): AmmMarketState => ({
    syReserve: props.market.state.syReserve,
    ptReserve: props.market.state.ptReserve,
    totalLp: props.market.state.totalLpSupply,
    scalarRoot: marketParams().scalarRoot,
    initialAnchor: props.market.metadata?.initialAnchor ?? props.market.state.lnImpliedRate,
    feeRate: marketParams().feeRate,
    expiry: BigInt(props.market.expiry),
    lastLnImpliedRate: props.market.state.lnImpliedRate,
  }));

  // Calculate swap quote using extracted pure function
  const swapResult = createMemo(() =>
    calculateSwapQuote(direction(), ammState(), parsedInputAmount())
  );

  // Extract values from swap result
  const expectedOutput = createMemo(() => swapResult()?.amountOut ?? BigInt(0));
  const priceImpact = createMemo(() => swapResult()?.priceImpact ?? 0);

  // Animate output for Change Blindness prevention (UI/UX Law)
  const numericOutput = createMemo(() => fromWad(expectedOutput()).toNumber());
  const animatedOutput = createAnimatedNumber(numericOutput, { duration: 300, decimals: 6 });
  const formattedAnimatedOutput = createMemo(() => {
    const value = animatedOutput();
    if (value === 0) return '0.000000';
    const formatted = value.toFixed(6);
    const parts = formatted.split('.');
    const intPart = parts[0] ?? '0';
    const decPart = parts[1];
    if (decPart !== undefined) {
      const trimmed = decPart.replace(/0+$/, '').padEnd(2, '0');
      return `${intPart}.${trimmed}`;
    }
    return formatted;
  });

  // Price impact severity
  const priceImpactSeverity = createMemo((): 'low' | 'medium' | 'high' | 'very-high' | 'extreme' => {
    const impact = priceImpact();
    if (impact < 0.01) return 'low';
    if (impact < 0.03) return 'medium';
    if (impact < 0.05) return 'high';
    if (impact < 0.1) return 'very-high';
    return 'extreme';
  });

  // Calculate implied APY change and derive display properties
  const impliedApyBefore = createMemo(() => getImpliedApy(props.market.state.lnImpliedRate));
  const impliedApyAfter = createMemo(() => {
    const result = swapResult();
    return result ? getImpliedApy(result.newLnImpliedRate) : impliedApyBefore();
  });

  // Pre-compute view models to simplify JSX
  const outputBadgeStyle = createMemo(() => deriveOutputBadgeStyle(tokenType(), isBuying()));

  // Calculate minimum output with slippage
  const minOutput = createMemo(() => calculateMinOutput(expectedOutput(), slippageBps()));

  // Validation - placeholder for balance checks
  // In a full implementation, these would use useTokenBalance hooks
  const hasInsufficientBalance = createMemo(() => false);
  const hasInsufficientCollateral = createMemo(() => false);
  const collateralRequired = createMemo(() =>
    direction() === 'sell_yt' ? parsedInputAmount() * BigInt(4) : BigInt(0)
  );

  // Price impact warning state
  const priceImpactCanProceed = createMemo(() => priceImpactSeverity() !== 'extreme');
  const priceImpactRequiresAck = createMemo(() =>
    priceImpactSeverity() === 'high' || priceImpactSeverity() === 'very-high'
  );
  const [priceImpactAcknowledged, setPriceImpactAcknowledged] = createSignal(false);

  const canSwap = createMemo(
    () =>
      isConnected() &&
      isValidAmount() &&
      !hasInsufficientBalance() &&
      !hasInsufficientCollateral() &&
      !isSwapping() &&
      !isSuccess() &&
      !props.market.isExpired &&
      priceImpactCanProceed()
  );

  // Pre-computed UI state using extracted pure function
  const uiState = createMemo(() =>
    deriveSwapFormUiState({
      isBuying: isBuying(),
      hasInsufficientBalance: hasInsufficientBalance(),
      isFlipping: isFlipping(),
      isValidAmount: isValidAmount(),
      priceImpactSeverity: priceImpactSeverity(),
      direction: direction(),
    })
  );

  // Derive button state using guard pattern (replaces nested ternaries)
  const buttonState = createMemo(() =>
    deriveButtonState({
      state: {
        isConnected: isConnected(),
        isValidAmount: isValidAmount(),
        hasInsufficientBalance: hasInsufficientBalance(),
        hasInsufficientCollateral: hasInsufficientCollateral(),
        isSwapping: isSwapping(),
        isSuccess: isSuccess(),
        isExpired: props.market.isExpired,
        priceImpactCanProceed: priceImpactCanProceed(),
        priceImpactRequiresAck: priceImpactRequiresAck(),
        priceImpactAcknowledged: priceImpactAcknowledged(),
      },
      tokenType: tokenType(),
      isBuying: isBuying(),
    })
  );

  // Handle swap
  const handleSwap = (): void => {
    if (!canSwap()) return;

    swap({
      marketAddress: props.market.address,
      syAddress: props.market.syAddress,
      ptAddress: props.market.ptAddress,
      ytAddress: props.market.ytAddress,
      direction: direction(),
      amountIn: parsedInputAmount(),
      minAmountOut: minOutput(),
    });
  };

  // Clear input on success
  createEffect(
    on(isSuccess, (success) => {
      if (success) {
        setInputAmount('');
      }
    })
  );

  // Handle direction change with animation
  const toggleDirection = (): void => {
    setIsFlipping(true);
    setTimeout(() => {
      setIsBuying((prev) => !prev);
      setInputAmount('');
      resetSwap();
      setPriceImpactAcknowledged(false);
      setIsFlipping(false);
    }, 150);
  };

  // Handle token type change with confirmation feedback
  const handleTokenTypeChange = (newType: string): void => {
    if (!isValidTokenType(newType)) return;
    setTokenType(newType);
    setInputAmount('');
    resetSwap();
    setPriceImpactAcknowledged(false);
    toast.success(`Switched to ${newType}`, {
      description: getTokenTypeDescription(newType),
      duration: 2000,
    });
  };

  // Handle buy/sell change with confirmation feedback
  const handleDirectionChange = (value: string): void => {
    if (!isValidBuySell(value)) return;
    const buying = value === 'buy';
    setIsBuying(buying);
    setInputAmount('');
    resetSwap();
    setPriceImpactAcknowledged(false);
    const dirLabel = buying ? 'Buy mode' : 'Sell mode';
    const description = buying
      ? `Pay SY to receive ${tokenType()}`
      : `Pay ${tokenType()} to receive SY`;
    toast.success(dirLabel, { description, duration: 2000 });
  };

  return (
    <FormLayout class={props.class} gradient={uiState().formGradient}>
      {/* Token type + direction as inline pills */}
      <div class="flex flex-wrap items-center justify-between gap-3">
        <ToggleGroup class="bg-muted rounded-lg p-1">
          <ToggleGroupItem
            pressed={tokenType() === 'PT'}
            onPressedChange={() => {
              handleTokenTypeChange('PT');
            }}
            class="data-[pressed]:bg-primary data-[pressed]:text-primary-foreground rounded-md px-4"
          >
            PT
          </ToggleGroupItem>
          <ToggleGroupItem
            pressed={tokenType() === 'YT'}
            onPressedChange={() => {
              handleTokenTypeChange('YT');
            }}
            class="data-[pressed]:bg-chart-2 data-[pressed]:text-foreground rounded-md px-4"
          >
            YT
          </ToggleGroupItem>
        </ToggleGroup>

        <ToggleGroup class="bg-muted rounded-lg p-1">
          <ToggleGroupItem
            pressed={isBuying()}
            onPressedChange={() => {
              handleDirectionChange('buy');
            }}
            class="data-[pressed]:bg-primary/20 data-[pressed]:text-primary rounded-md px-4"
          >
            Buy
          </ToggleGroupItem>
          <ToggleGroupItem
            pressed={!isBuying()}
            onPressedChange={() => {
              handleDirectionChange('sell');
            }}
            class="data-[pressed]:bg-destructive/20 data-[pressed]:text-destructive rounded-md px-4"
          >
            Sell
          </ToggleGroupItem>
        </ToggleGroup>
      </div>

      {/* Near-expiry warning banner */}
      <Show when={!props.market.isExpired}>
        <NearExpiryWarning expiryTimestamp={props.market.expiry} context="swap" />
      </Show>

      {/* Input Section */}
      <FormInputSection>
        <NumberInput
          label="You pay"
          value={inputAmount()}
          onChange={setInputAmount}
          placeholder="0.00"
          error={uiState().inputError}
          rightElement={
            <span class="text-muted-foreground text-sm font-medium">{inputLabel()}</span>
          }
        />
      </FormInputSection>

      {/* Animated swap direction button */}
      <FormDivider>
        <div class="bg-background absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
          <Button
            variant="outline"
            size="icon"
            onClick={toggleDirection}
            class={cn(
              'bg-background h-10 w-10 rounded-full shadow-lg transition-transform duration-300',
              uiState().flipButtonClass
            )}
            aria-label="Toggle swap direction"
          >
            <ArrowUpDownIcon class="h-4 w-4" />
          </Button>
        </div>
      </FormDivider>

      {/* Output Preview */}
      <FormOutputSection>
        <div class="flex items-center justify-between gap-2">
          <span class="text-muted-foreground shrink-0 text-sm">You receive</span>
          <span class="text-muted-foreground truncate text-xs">
            Min: {formatWad(minOutput(), 4)}
          </span>
        </div>
        <div class="flex items-center gap-2">
          <span class="text-foreground min-w-0 flex-1 truncate font-mono text-2xl font-semibold tabular-nums">
            {formattedAnimatedOutput()}
          </span>
          {/* Token badge - using pre-computed styles */}
          <div
            class={cn(
              'flex h-10 shrink-0 items-center justify-center rounded-full px-3',
              'border-border/50 border',
              outputBadgeStyle().containerClass
            )}
          >
            <span class={cn('font-mono text-sm font-semibold', outputBadgeStyle().textClass)}>
              {outputBadgeStyle().displayText}
            </span>
          </div>
        </div>
      </FormOutputSection>

      {/* Price Impact Display */}
      <Show when={isValidAmount()}>
        <div class="space-y-2">
          <FormRow
            label="Price Impact"
            labelClass="text-sm"
            valueClass={cn(
              'text-sm font-medium',
              priceImpactSeverity() === 'low' && 'text-muted-foreground',
              priceImpactSeverity() === 'medium' && 'text-warning',
              priceImpactSeverity() === 'high' && 'text-orange-500',
              priceImpactSeverity() === 'very-high' && 'text-destructive',
              priceImpactSeverity() === 'extreme' && 'text-destructive font-bold'
            )}
            value={`${(priceImpact() * 100).toFixed(2)}%`}
          />
          <FormRow
            label="Rate"
            labelClass="text-sm"
            valueClass="text-sm text-muted-foreground"
            value={`1 ${inputLabel()} = ${
              parsedInputAmount() > 0n
                ? (Number(expectedOutput()) / Number(parsedInputAmount())).toFixed(4)
                : '-'
            } ${outputLabel()}`}
          />
          <Show when={direction() === 'buy_pt' || direction() === 'sell_pt'}>
            <FormRow
              label="Implied APY"
              labelClass="text-sm"
              valueClass={cn(
                'text-sm',
                impliedApyAfter() > impliedApyBefore() && 'text-primary',
                impliedApyAfter() < impliedApyBefore() && 'text-destructive'
              )}
              value={`${(impliedApyBefore() * 100).toFixed(2)}% → ${(impliedApyAfter() * 100).toFixed(2)}%`}
            />
          </Show>
        </div>
      </Show>

      {/* Slippage Settings */}
      <div>
        <div class="text-muted-foreground mb-2 text-sm">Slippage Tolerance</div>
        <ToggleGroup class="flex gap-1">
          {SLIPPAGE_OPTIONS.map((option) => (
            <ToggleGroupItem
              pressed={slippageBps() === option.value}
              onPressedChange={() => {
                setSlippageBps(option.value);
              }}
              variant="outline"
              size="sm"
            >
              {option.label}
            </ToggleGroupItem>
          ))}
        </ToggleGroup>
      </div>

      {/* YT Sell Collateral Warning */}
      <Show when={uiState().showYtCollateralWarning}>
        <div class="bg-warning/10 border-warning/30 text-warning-foreground rounded-lg border p-3 text-sm">
          <p class="font-medium">Collateral Required</p>
          <p class="text-warning-foreground/80 mt-1">
            Selling YT requires {formatWad(collateralRequired(), 2)} {syLabel()} as collateral.
            This will be returned after the swap.
          </p>
        </div>
      </Show>

      {/* Transaction Status */}
      <Show when={isSwapping() || isSuccess() || isError()}>
        <div
          class={cn(
            'rounded-lg border p-3 text-sm',
            isSwapping() && 'border-primary/30 bg-primary/10',
            isSuccess() && 'border-success/30 bg-success/10',
            isError() && 'border-destructive/30 bg-destructive/10'
          )}
        >
          <Show when={isSwapping()}>
            <p class="text-primary font-medium">Transaction pending...</p>
          </Show>
          <Show when={isSuccess()}>
            <p class="text-success font-medium">Swap successful!</p>
            <Show when={transactionHash()}>
              <p class="text-success/80 mt-1 truncate text-xs">
                Tx: {transactionHash()}
              </p>
            </Show>
          </Show>
          <Show when={isError()}>
            <p class="text-destructive font-medium">Transaction failed</p>
            <Show when={error()}>
              <p class="text-destructive/80 mt-1 text-xs">{error()?.message}</p>
            </Show>
          </Show>
        </div>
      </Show>

      {/* Submit Button */}
      <FormActions>
        <Button
          onClick={handleSwap}
          disabled={buttonState().disabled}
          loading={isSwapping()}
          size="xl"
          class={cn('w-full', uiState().sellButtonClass)}
        >
          {buttonState().label}
        </Button>
      </FormActions>
    </FormLayout>
  );
}

// packages/frontend/src/components/forms/SwapForm.tsx
'use client';

import BigNumber from 'bignumber.js';
import { type ReactNode, useEffect, useMemo, useState } from 'react';

import { PriceImpactWarning, usePriceImpactWarning } from '@/components/display/PriceImpactWarning';
import { TxStatus } from '@/components/display/TxStatus';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { useStarknet } from '@/hooks/useStarknet';
import { calculateMinOutput, type SwapDirection, useSwap } from '@/hooks/useSwap';
import { useTokenBalance } from '@/hooks/useTokenBalance';
import { getMarketParams } from '@/lib/constants/addresses';
import {
  calcSwapExactPtForSy,
  calcSwapExactSyForPt,
  calcSwapSyForExactPt,
  formatPriceImpact,
  getImpliedApy,
  getPriceImpactSeverity,
  type MarketState as AmmMarketState,
  type SwapResult,
} from '@/lib/math/amm';
import { formatWad, parseWad, WAD_BIGINT } from '@/lib/math/wad';
import type { MarketData } from '@/types/market';

import { TokenInput } from './TokenInput';

interface SwapFormProps {
  market: MarketData;
}

const SLIPPAGE_OPTIONS = [
  { label: '0.1%', value: 10 },
  { label: '0.5%', value: 50 },
  { label: '1%', value: 100 },
];

type TokenType = 'PT' | 'YT';

export function SwapForm({ market }: SwapFormProps): ReactNode {
  const { isConnected, network } = useStarknet();
  const [tokenType, setTokenType] = useState<TokenType>('PT');
  const [isBuying, setIsBuying] = useState(true);
  const [inputAmount, setInputAmount] = useState('');
  const [slippageBps, setSlippageBps] = useState(50); // 0.5% default

  // Derive swap direction from token type and buy/sell
  const direction: SwapDirection = isBuying
    ? tokenType === 'PT'
      ? 'buy_pt'
      : 'buy_yt'
    : tokenType === 'PT'
      ? 'sell_pt'
      : 'sell_yt';

  const {
    swap,
    isSwapping,
    isSuccess,
    isError,
    error,
    transactionHash,
    reset: resetSwap,
  } = useSwap();

  // Get token symbol from metadata - hide SY, just show underlying
  const tokenSymbol = market.metadata?.yieldTokenSymbol ?? 'Token';
  const underlyingLabel = tokenSymbol; // Use underlying symbol instead of SY
  const ptLabel = `PT-${tokenSymbol}`;
  const ytLabel = `YT-${tokenSymbol}`;

  // Get input/output token addresses and labels based on direction
  const inputToken = isBuying
    ? market.syAddress
    : tokenType === 'PT'
      ? market.ptAddress
      : market.ytAddress;
  const inputLabel = isBuying ? underlyingLabel : tokenType === 'PT' ? ptLabel : ytLabel;
  const outputLabel = isBuying ? (tokenType === 'PT' ? ptLabel : ytLabel) : underlyingLabel;

  // Fetch balance for input token
  const { data: inputBalance } = useTokenBalance(inputToken);

  // For selling YT, we also need SY balance for collateral
  const { data: syBalance } = useTokenBalance(market.syAddress);

  // Get market params for AMM calculations
  const marketParams = useMemo(() => getMarketParams(network), [network]);

  // Parse input amount
  const parsedInputAmount = useMemo(() => {
    if (!inputAmount || inputAmount === '') return BigInt(0);
    try {
      return parseWad(inputAmount);
    } catch {
      return BigInt(0);
    }
  }, [inputAmount]);

  // Build AMM market state for accurate calculations
  const ammState: AmmMarketState = useMemo(
    () => ({
      syReserve: market.state.syReserve,
      ptReserve: market.state.ptReserve,
      totalLp: market.state.totalLpSupply,
      scalarRoot: marketParams.scalarRoot,
      // Use market-specific initialAnchor from metadata, or current ln rate as fallback
      initialAnchor: market.metadata?.initialAnchor ?? market.state.lnImpliedRate,
      feeRate: marketParams.feeRate,
      expiry: BigInt(market.expiry),
      lastLnImpliedRate: market.state.lnImpliedRate,
    }),
    [market.state, market.expiry, market.metadata?.initialAnchor, marketParams]
  );

  // Calculate swap quote using accurate AMM math
  const swapResult: SwapResult | null = useMemo(() => {
    if (parsedInputAmount === BigInt(0)) return null;

    const { syReserve, ptReserve } = market.state;
    if (syReserve === BigInt(0) || ptReserve === BigInt(0)) return null;

    try {
      if (direction === 'buy_pt') {
        // Buy PT with SY - use accurate AMM calculation
        return calcSwapExactSyForPt(ammState, parsedInputAmount);
      } else if (direction === 'sell_pt') {
        // Sell PT for SY - use accurate AMM calculation
        return calcSwapExactPtForSy(ammState, parsedInputAmount);
      } else if (direction === 'buy_yt') {
        // Buy YT with SY via flash swap
        // Step 1: Mint PT+YT from SY (1:1)
        // Step 2: Sell PT back to market
        // Net result: YT amount ≈ SY_in, cost = SY_in - PT_sale_proceeds
        // For estimation: YT_out ≈ SY_in (since minted 1:1)
        // Use PT price to estimate net cost
        const ptSaleResult = calcSwapExactPtForSy(ammState, parsedInputAmount);
        // YT out = amount minted (same as SY in, since 1:1 mint)
        // Effective cost = SY_in - SY_recovered_from_PT_sale
        return {
          amountOut: parsedInputAmount, // YT received = SY deposited for minting
          fee: ptSaleResult.fee,
          newLnImpliedRate: ptSaleResult.newLnImpliedRate,
          priceImpact: ptSaleResult.priceImpact,
          effectivePrice:
            parsedInputAmount > 0n
              ? ((parsedInputAmount - ptSaleResult.amountOut) * WAD_BIGINT) / parsedInputAmount
              : WAD_BIGINT, // Cost per YT
          spotPrice: WAD_BIGINT - ptSaleResult.spotPrice, // YT price ≈ 1 - PT price
        };
      } else {
        // Sell YT for SY via flash swap
        // Step 1: Buy PT to match YT amount (need parsedInputAmount PT to pair with YT)
        // Step 2: Redeem PT+YT for SY (1:1 redemption gives parsedInputAmount SY)
        // Net result: SY_out = redemption_value - PT_purchase_cost
        const ptNeeded = parsedInputAmount; // Need PT equal to YT amount to redeem

        // Calculate SY cost to buy the required PT using exact output function
        const ptPurchaseResult = calcSwapSyForExactPt(ammState, ptNeeded);
        const syNeededForPt = ptPurchaseResult.amountOut; // SY required to buy PT

        // After redemption, we get ptNeeded SY (1:1), minus what we spent buying PT
        const syOut = ptNeeded > syNeededForPt ? ptNeeded - syNeededForPt : 0n;

        return {
          amountOut: syOut,
          fee: ptPurchaseResult.fee,
          newLnImpliedRate: ptPurchaseResult.newLnImpliedRate,
          priceImpact: ptPurchaseResult.priceImpact,
          effectivePrice: syOut > 0n ? (syNeededForPt * WAD_BIGINT) / syOut : WAD_BIGINT,
          spotPrice: WAD_BIGINT - ptPurchaseResult.spotPrice, // YT price ≈ 1 - PT price
        };
      }
    } catch {
      return null;
    }
  }, [parsedInputAmount, market.state, direction, ammState]);

  // Extract values from swap result
  const expectedOutput = swapResult?.amountOut ?? BigInt(0);
  const priceImpact = swapResult?.priceImpact ?? 0;
  const priceImpactSeverity = getPriceImpactSeverity(priceImpact);

  // Price impact warning management
  const priceImpactWarning = usePriceImpactWarning(priceImpact);

  // Calculate implied APY change
  const impliedApyBefore = getImpliedApy(market.state.lnImpliedRate);
  const impliedApyAfter = swapResult
    ? getImpliedApy(swapResult.newLnImpliedRate)
    : impliedApyBefore;

  // Calculate minimum output with slippage
  const minOutput = useMemo(() => {
    return calculateMinOutput(expectedOutput, slippageBps);
  }, [expectedOutput, slippageBps]);

  // Validation
  const hasInsufficientBalance = inputBalance !== undefined && parsedInputAmount > inputBalance;
  const isValidAmount = parsedInputAmount > BigInt(0);

  // For selling YT, check collateral requirement (4x the YT amount)
  const collateralRequired = direction === 'sell_yt' ? parsedInputAmount * BigInt(4) : BigInt(0);
  const hasInsufficientCollateral =
    direction === 'sell_yt' && syBalance !== undefined && collateralRequired > syBalance;

  const canSwap =
    isConnected &&
    isValidAmount &&
    !hasInsufficientBalance &&
    !hasInsufficientCollateral &&
    !isSwapping &&
    !isSuccess &&
    priceImpactWarning.canProceed;

  // Determine transaction status for TxStatus component
  const txStatus = useMemo(() => {
    if (isSwapping) return 'pending' as const;
    if (isSuccess) return 'success' as const;
    if (isError) return 'error' as const;
    return 'idle' as const;
  }, [isSwapping, isSuccess, isError]);

  // Handle swap
  const handleSwap = (): void => {
    if (!canSwap) return;

    swap({
      marketAddress: market.address,
      syAddress: market.syAddress,
      ptAddress: market.ptAddress,
      ytAddress: market.ytAddress,
      direction,
      amountIn: parsedInputAmount,
      minAmountOut: minOutput,
    });
  };

  // Clear input on success
  useEffect(() => {
    if (isSuccess) {
      setInputAmount('');
    }
  }, [isSuccess]);

  // Handle direction change (flip buy/sell)
  const toggleDirection = (): void => {
    setIsBuying((prev) => !prev);
    setInputAmount('');
    resetSwap();
    priceImpactWarning.reset();
  };

  // Handle token type change
  const handleTokenTypeChange = (newType: TokenType): void => {
    setTokenType(newType);
    setInputAmount('');
    resetSwap();
    priceImpactWarning.reset();
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Swap</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Token Type Selector (PT vs YT) */}
        <Tabs
          value={tokenType}
          onValueChange={(value) => {
            handleTokenTypeChange(value as TokenType);
          }}
          className="w-full"
        >
          <TabsList className="w-full">
            <TabsTrigger value="PT" className="flex-1">
              PT (Principal)
            </TabsTrigger>
            <TabsTrigger value="YT" className="flex-1">
              YT (Yield)
            </TabsTrigger>
          </TabsList>
        </Tabs>

        {/* Buy/Sell Toggle */}
        <Tabs
          value={isBuying ? 'buy' : 'sell'}
          onValueChange={(value) => {
            setIsBuying(value === 'buy');
            setInputAmount('');
            resetSwap();
            priceImpactWarning.reset();
          }}
          className="w-full"
        >
          <TabsList className="w-full">
            <TabsTrigger
              value="buy"
              className="data-active:bg-primary data-active:text-primary-foreground flex-1"
            >
              Buy {tokenType}
            </TabsTrigger>
            <TabsTrigger
              value="sell"
              className="data-active:bg-destructive data-active:text-primary-foreground flex-1"
            >
              Sell {tokenType}
            </TabsTrigger>
          </TabsList>
        </Tabs>

        {/* Input Token */}
        <TokenInput
          label={`From (${inputLabel})`}
          tokenAddress={inputToken}
          tokenSymbol={inputLabel}
          value={inputAmount}
          onChange={setInputAmount}
          error={hasInsufficientBalance ? 'Insufficient balance' : undefined}
        />

        {/* Swap Direction Indicator */}
        <div className="flex justify-center">
          <Button
            variant="ghost"
            size="icon"
            onClick={toggleDirection}
            className="rounded-full"
            aria-label="Toggle swap direction"
          >
            <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4"
              />
            </svg>
          </Button>
        </div>

        {/* Output Preview */}
        <Card size="sm" className="bg-muted">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <span className="text-muted-foreground text-sm">To ({outputLabel})</span>
              <span className="text-muted-foreground text-sm">
                Min: {formatWad(minOutput, 6)} {outputLabel}
              </span>
            </div>
            <div className="text-foreground mt-2 text-2xl font-semibold">
              {formatWad(expectedOutput, 6)} {outputLabel}
            </div>
          </CardContent>
        </Card>

        {/* Price Impact & Rate */}
        {isValidAmount && (
          <Card size="sm" className="bg-muted/30">
            <CardContent className="space-y-2 p-3 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Rate</span>
                <span className="text-foreground">
                  1 {inputLabel} ={' '}
                  {parsedInputAmount > BigInt(0)
                    ? new BigNumber(expectedOutput.toString())
                        .dividedBy(parsedInputAmount.toString())
                        .toFixed(6)
                    : '0'}{' '}
                  {outputLabel}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Price Impact</span>
                <span
                  className={
                    priceImpactSeverity === 'very-high'
                      ? 'text-destructive font-medium'
                      : priceImpactSeverity === 'high'
                        ? 'text-destructive'
                        : priceImpactSeverity === 'medium'
                          ? 'text-chart-1'
                          : 'text-foreground'
                  }
                >
                  {formatPriceImpact(priceImpact)}
                </span>
              </div>
              {/* Implied APY Change */}
              {(direction === 'buy_pt' || direction === 'sell_pt') && (
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Implied APY</span>
                  <span className="text-foreground">
                    {(impliedApyBefore * 100).toFixed(2)}%{' '}
                    <span className="text-muted-foreground">→</span>{' '}
                    <span
                      className={
                        impliedApyAfter > impliedApyBefore
                          ? 'text-primary'
                          : impliedApyAfter < impliedApyBefore
                            ? 'text-destructive'
                            : ''
                      }
                    >
                      {(impliedApyAfter * 100).toFixed(2)}%
                    </span>
                  </span>
                </div>
              )}
              <div className="flex justify-between">
                <span className="text-muted-foreground">Slippage Tolerance</span>
                <span className="text-foreground">{slippageBps / 100}%</span>
              </div>
              {/* Fee info */}
              {swapResult && swapResult.fee > 0n && (
                <div className="text-muted-foreground flex justify-between">
                  <span>Swap Fee</span>
                  <span>{formatWad(swapResult.fee, 6)}</span>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Price Impact Warning */}
        {isValidAmount && priceImpactWarning.severity !== 'low' && (
          <PriceImpactWarning
            priceImpact={priceImpact}
            onAcknowledge={priceImpactWarning.acknowledge}
            acknowledged={priceImpactWarning.acknowledged}
          />
        )}

        {/* Slippage Settings */}
        <div>
          <div className="text-muted-foreground mb-2 text-sm">Slippage Tolerance</div>
          <ToggleGroup className="flex gap-1">
            {SLIPPAGE_OPTIONS.map((option) => (
              <ToggleGroupItem
                key={option.value}
                pressed={slippageBps === option.value}
                onPressedChange={() => {
                  setSlippageBps(option.value);
                }}
                variant="outline"
                size="sm"
              >
                {option.label}
              </ToggleGroupItem>
            ))}
          </ToggleGroup>
        </div>

        {/* YT Sell Collateral Warning */}
        {direction === 'sell_yt' && isValidAmount && (
          <Card size="sm" className="border-chart-1/30 bg-chart-1/10">
            <CardContent className="flex items-start gap-2 p-3 text-sm">
              <svg
                className="text-chart-1 mt-0.5 h-4 w-4 shrink-0"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
              <div>
                <p className="text-chart-1 font-medium">Collateral Required</p>
                <p className="text-chart-1/80 mt-1">
                  Selling YT requires {formatWad(collateralRequired, 4)} {underlyingLabel} as
                  temporary collateral. This will be refunded after the swap.
                </p>
                {hasInsufficientCollateral && (
                  <p className="text-destructive mt-1">
                    Insufficient {underlyingLabel} balance. You have {formatWad(syBalance, 4)}.
                  </p>
                )}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Transaction Status */}
        {txStatus !== 'idle' && (
          <TxStatus status={txStatus} txHash={transactionHash ?? null} error={error} />
        )}

        {/* Submit Button */}
        <Button onClick={handleSwap} disabled={!canSwap || isSwapping} className="w-full">
          {isSwapping
            ? 'Swapping...'
            : !isConnected
              ? 'Connect Wallet'
              : !isValidAmount
                ? 'Enter Amount'
                : hasInsufficientBalance
                  ? 'Insufficient Balance'
                  : hasInsufficientCollateral
                    ? 'Insufficient Collateral'
                    : priceImpactWarning.requiresAcknowledgment && !priceImpactWarning.acknowledged
                      ? 'Acknowledge Price Impact'
                      : isSuccess
                        ? 'Swapped!'
                        : `Swap ${inputLabel} for ${outputLabel}`}
        </Button>
      </CardContent>
    </Card>
  );
}
