// packages/frontend/src/components/wallet/ConnectButton.tsx
'use client';

import { useStarknet } from '@/hooks/useStarknet';
import { formatAddress } from '@/lib/starknet/wallet';

import { Button } from '../ui/Button';

export function ConnectButton(): React.ReactNode {
  const { address, isConnected, isConnecting, connect, disconnect } = useStarknet();

  if (isConnected && address) {
    return (
      <Button variant="secondary" onClick={() => void disconnect()}>
        {formatAddress(address)}
      </Button>
    );
  }

  return (
    <Button onClick={() => void connect()} disabled={isConnecting}>
      {isConnecting ? 'Connecting...' : 'Connect Wallet'}
    </Button>
  );
}

// packages/frontend-solid/src/features/wallet/ui/ConnectButton.tsx
import { formatAddress } from '@shared/starknet/wallet';
import { Button } from '@shared/ui/Button';
import { type JSX, Show } from 'solid-js';
import { useStarknet } from '../model/useStarknet';

/**
 * Wallet connection button that displays connection status.
 *
 * - Shows "Connect Wallet" when disconnected
 * - Shows "Connecting..." while connecting
 * - Shows truncated address when connected (click to disconnect)
 */
export function ConnectButton(): JSX.Element {
  const { address, isConnected, isConnecting, connect, disconnect } = useStarknet();

  const handleConnect = (): void => {
    void connect();
  };

  const handleDisconnect = (): void => {
    void disconnect();
  };

  return (
    <Show
      when={isConnected() && address()}
      fallback={
        <Button onClick={handleConnect} disabled={isConnecting()} loading={isConnecting()}>
          {isConnecting() ? 'Connecting...' : 'Connect Wallet'}
        </Button>
      }
    >
      <Button variant="secondary" onClick={handleDisconnect}>
        {formatAddress(address() ?? '')}
      </Button>
    </Show>
  );
}
